server:
  port: 8081

spring:
  application:
    name: statementservice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/carddb
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

